### ISSUE TITLE
Parrot ANAFI beacon frames not being dissected.

### ISSUE THREAD

**Issue by pierreSCpapon** [opendroneid/wireshark-dissector#1]
Thank you for your work and support in the ESP-32 RID port.
I did not want to derail the issue posted there any further with dissector discussions. [Here for reference.](https://github.com/sxjack/uav_electronic_ids/issues/9#issuecomment-978862861)

I understand the difference between beacon broadcast frames vs probe responses however, [in the capture posted earlier](https://github.com/sxjack/uav_electronic_ids/files/7592982/parrotESPlinuxFilter.zip), the dissector is not picking up the beacon broadcast frame from the Parrot ANAFI.

![Screenshot 2021-11-25 155625](https://user-images.githubusercontent.com/78420302/143394190-18d0e305-a896-43ab-a8a3-b4e9b40cd174.png)
For example, packet number 202:

> shall (BWFB0020) encode the Remote ID message pack as a vendor specific information element IE221 (using OUI: FA-0B-BC, Vendor Type: 0x0D)

As far as I can tell this is satisfied and since wireshark identifies the packet as beacon frame, the following also checks out:

>  0x80 0x00 at offset 0x12

I hope I am not missing something obvious but wanted to report what I was facing. Once again, thank you.

**Comment by gabrielcox** [comment]
Fixed in [this commit](https://github.com/opendroneid/wireshark-dissector/commit/e3ed8111eb22768eb1f5bb1bbef79897f179e64d).
The dissector wasn't properly iterating through every vendor specific tag.  If the first one (VSIE) wasn't RID it was ignoring the rest of the frame.  It will now iterate through each tag.

@friissoren , we may want to ensure the Anrdoid receiver does this (if it doesn't already).  I don't think the standard (implicitly or explicitly) *requires* only a single vendor specific tag.

**Comment by pierreSCpapon** [comment]
Thank you @gabrielcox I confirmed this is working now!

**Comment by friissoren** [comment]
Just for completion of this discussion. The Android receiver already checks through all vendor information elements that gets passed to it in the scan result data that the lower Android layers passes to the app.
