### ISSUE TITLE
Lua script compile issues

### ISSUE THREAD

**Issue by viet-nguyen-matternet** [opendroneid/wireshark-dissector#7]
Does part of the installation include compiling the lua library first?

I am experiencing an issue where I am unable to compile the lua script to create the library for wireshark to use.

I have cloned the repo to the Personal Plugins folder following instructions here.
https://www.wireshark.org/docs/wsug_html_chunked/ChPluginFolders.html

But notice that the plugin is not discovered after restart of Wireshark. From the link posted earlier it looks like the lua script should be compiled first. 

I attempted to compile but ran into this error:

```
root@vwnguyen-ThinkPad-X1-Carbon-5th:/usr/local/lib/wireshark/plugins/3.6/wireshark-dissector(main)# lua opendroneid-dissector.lua 
lua: opendroneid-dissector.lua:7: attempt to call global 'Proto' (a nil value)
stack traceback:
	opendroneid-dissector.lua:7: in main chunk
	[C]: ?

```

Is this expected? How does one compile the lua script? Any help would be appreciated

**Comment by gabrielcox** [comment]
It appears like it was properly attempting to compile, but ran into an error.  What (exact) version and OS are you using and I can attempt to reproduce.
It sounds like you did everything right.

**Comment by viet-nguyen-matternet** [comment]
Thans for getting back to me.

Wireshark version: Wireshark 3.6.6 (Git commit 7d96674e2a30)
OS: Ubuntu 18.04

Steps taken:
1. Clone repo into personal plugins folder.
![image](https://user-images.githubusercontent.com/72229204/183716214-3dfd0778-606b-4799-8a02-4de5d06a74fb.png)
![image](https://user-images.githubusercontent.com/72229204/183716035-8ea90da9-58d0-4f1a-9495-89515627eee5.png)
2. Start capturing / sniffing.
3. Press "CTRL+L" or "CTRL+SHIFT+L" to attempt to load the plugin.
4. Observe a packet, see there is no dissection for the Remote ID message.
![image](https://user-images.githubusercontent.com/72229204/183717760-302f262a-e896-42ed-9366-847afe1ae177.png)

Additional note, Wireshark does not seem to pick up on it in the plugins folder.
![image](https://user-images.githubusercontent.com/72229204/183718025-815f1ab3-8af7-40cc-aabe-78b16e4b3e12.png)

**Comment by gabrielcox** [comment]
I just realized what you were doing in calling the lua compiler directly.  I think that fails due to the native lua libraries do not recognize the wireshark specific class (Proto).  So that's normal.  There is no need to pre-compile the lua script.  Wireshark will take care of this (when it's working properly).  I'll attempt to reproduce.

**Comment by viet-nguyen-matternet** [comment]
Just checking, is there any update to this issue?

**Comment by gabrielcox** [comment]
I had to reset up a Linux system to repeat this.  I have it running now, so still some research to be done on this.  I expect to have some answer tomorrow.

**Comment by gabrielcox** [comment]
@viet-nguyen-matternet , Ok, I have my linux system somewhat running now.  Try looking in "View->Internals->Supported Protocols".  Scroll down.  Do you should see "OPENDRONEID" in the proper place?  See pic below.

![image](https://user-images.githubusercontent.com/13051211/186043428-b08d159b-1b53-4121-bec5-3e3ee3102d14.png)

**Comment by viet-nguyen-matternet** [comment]
Hey @gabrielcox, I dont see it in that folder. I assume you followed the same steps I did when setting up your Wireshark. Maybe this is an unstable Wireshark version: Wireshark 3.6.6 (Git commit 7d96674e2a30).

**Comment by gabrielcox** [comment]
@viet-nguyen-matternet 
Ok, I think I see something that I didn't notice before.  How did you install Wireshark?
In my test, I just installed Ubuntu 20.04, and did an "apt-get install wireshark".  That's it.  It installed Wireshark 3.2.3 which includes the Lua Support.
When you click on the Tools menu, do you even see the Lua option?
![image](https://user-images.githubusercontent.com/13051211/186489698-34ac081c-40b0-4466-8a63-24c7e03ba3ad.png)

Also, there should be a path for personal Lua plugins:
![image](https://user-images.githubusercontent.com/13051211/186491113-9271cae3-5433-4fbc-816b-3229c8f4b489.png)

It is normal for the Lua script to not show up in "plugins".  (It does not in mine).  The Lua engine should be integrated in Wireshark, and it will interpret your scripts at runtime -- no need to compile.

If you clone the wireshark dissector under the Lua Plugins directory, and the Wireshark you are running has the integrated Lua interpreter installed, it should work.  The apt-installed version seems to have this.  

I generally sudo run wireshark so that I don't have permission problems in promiscuous/monitor mode, but I'm unsure if this is always necessary (if you get permissions set right elsewhere).

**Comment by viet-nguyen-matternet** [comment]
Ah I see that I dont have the Lua option. "apt-get install wireshark" installs a 3.6.5 version. I also separately built the 3.2.3 version of wireshark to no avail. 

I am thinking the Lua option may only be available in Ubuntu 20.04 and not Ubuntu 18.04

**Comment by viet-nguyen-matternet** [comment]
Resolved this.

Downloaded Wireshark 3.2.3
Followed Setup [[How to configure lua after Wireshark was installed (Linux)](https://stackoverflow.com/questions/58977433/how-to-configure-lua-after-wireshark-was-installed-linux)](https://stackoverflow.com/questions/58977433/how-to-configure-lua-after-wireshark-was-installed-linux)
Build Wireshark 3.2.3

Happy sniffing :)

![image](https://user-images.githubusercontent.com/72229204/186538426-b57c4f07-e416-4963-93bf-a7544cb960bb.png)


Thanks for helping narrow it down @gabrielcox!

**Comment by gabrielcox** [comment]
@viet-nguyen-matternet 
Great job figuring that out. Thank you for posting the solution to the issue. I'm happy to see your parsed packets!
